/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class aiss_blackbox_BlackBoxUtil */

#ifndef _Included_aiss_blackbox_BlackBoxUtil
#define _Included_aiss_blackbox_BlackBoxUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     aiss_blackbox_BlackBoxUtil
 * Method:    encrypt
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_aiss_blackbox_BlackBoxUtil_cypher
  (JNIEnv *, jclass, jstring, jstring, jstring);


#ifdef __cplusplus
}
#endif
#endif
